export const words = {
  en: [
    { word: 'Cheetah',     hint: 'Spotted' },
    { word: 'Piano',       hint: 'Ivory' },
    { word: 'Submarine',   hint: 'Sonar' },
    { word: 'Volcano',     hint: 'Rupture' },
    { word: 'Telescope',   hint: 'Cosmic' },
    { word: 'Sushi',       hint: 'Roll' },
    { word: 'Lightning',   hint: 'Volt' },
    { word: 'Diamond',     hint: 'Pressure' },
    { word: 'Tornado',     hint: 'Vortex' },
    { word: 'Cactus',      hint: 'Prickly' },
    { word: 'Lighthouse',  hint: 'Beacon' },
    { word: 'Saxophone',   hint: 'Brass' },
    { word: 'Giraffe',     hint: 'Altitude' },
    { word: 'Iceberg',     hint: 'Titanic' },
    { word: 'Fireworks',   hint: 'Spark' },
    { word: 'Quicksand',   hint: 'Suction' },
    { word: 'Compass',     hint: 'Azimuth' },
    { word: 'Bonsai',      hint: 'Miniature' },
    { word: 'Avalanche',   hint: 'Cascade' },
    { word: 'Accordion',   hint: 'Squeeze' },
    { word: 'Boomerang',   hint: 'Karma' },
    { word: 'Floor',       hint: 'Ceiling' },
    { word: 'Mirage',      hint: 'Illusion' },
    { word: 'Gold',        hint: 'Rich' },
    { word: 'Chameleon',   hint: 'Blending' },
    { word: 'Trump',       hint: 'Toupee' },
    { word: 'Sex',         hint: 'Friction' },
    { word: 'Ex',          hint: 'Regret' },
    { word: 'OnlyFans',    hint: 'Subscription' },
    { word: 'Tinder',      hint: 'Swipe' },
  ],

  es: [
    { word: 'Guepardo',          hint: 'Manchado' },
    { word: 'Piano',             hint: 'Marfil' },
    { word: 'Submarino',         hint: 'Sonar' },
    { word: 'Volcán',            hint: 'Erupción' },
    { word: 'Telescopio',        hint: 'Cósmico' },
    { word: 'Sushi',             hint: 'Rollo' },
    { word: 'Rayo',              hint: 'Voltio' },
    { word: 'Diamante',          hint: 'Presión' },
    { word: 'Tornado',           hint: 'Vórtice' },
    { word: 'Cactus',            hint: 'Espinoso' },
    { word: 'Faro',              hint: 'Baliza' },
    { word: 'Saxofón',           hint: 'Latón' },
    { word: 'Jirafa',            hint: 'Altitud' },
    { word: 'Iceberg',           hint: 'Titanic' },
    { word: 'Fuegos artificiales', hint: 'Chispa' },
    { word: 'Arena movediza',    hint: 'Succión' },
    { word: 'Brújula',           hint: 'Acimut' },
    { word: 'Bonsái',            hint: 'Miniatura' },
    { word: 'Avalancha',         hint: 'Cascada' },
    { word: 'Acordeón',          hint: 'Comprimir' },
    { word: 'Boomerang',         hint: 'Karma' },
    { word: 'Suelo',             hint: 'Techo' },
    { word: 'Espejismo',         hint: 'Ilusión' },
    { word: 'Oro',               hint: 'Rico' },
    { word: 'Camaleón',          hint: 'Camuflaje' },
    { word: 'Trump',             hint: 'Tupé' },
    { word: 'Sexo',              hint: 'Fricción' },
    { word: 'Ex',                hint: 'Arrepentimiento' },
    { word: 'OnlyFans',          hint: 'Suscripción' },
    { word: 'Tinder',            hint: 'Deslizar' },
  ],

  it: [
    { word: 'Ghepardo',          hint: 'Maculato' },
    { word: 'Pianoforte',        hint: 'Avorio' },
    { word: 'Sottomarino',       hint: 'Sonar' },
    { word: 'Vulcano',           hint: 'Eruzione' },
    { word: 'Telescopio',        hint: 'Cosmico' },
    { word: 'Sushi',             hint: 'Rotolo' },
    { word: 'Fulmine',           hint: 'Volt' },
    { word: 'Diamante',          hint: 'Pressione' },
    { word: 'Tornado',           hint: 'Vortice' },
    { word: 'Cactus',            hint: 'Spinoso' },
    { word: 'Faro',              hint: 'Segnale' },
    { word: 'Sassofono',         hint: 'Ottone' },
    { word: 'Giraffa',           hint: 'Altitudine' },
    { word: 'Iceberg',           hint: 'Titanic' },
    { word: "Fuochi d'artificio", hint: 'Scintilla' },
    { word: 'Sabbie mobili',     hint: 'Aspirazione' },
    { word: 'Bussola',           hint: 'Azimuth' },
    { word: 'Bonsai',            hint: 'Miniatura' },
    { word: 'Valanga',           hint: 'Cascata' },
    { word: 'Fisarmonica',       hint: 'Soffietto' },
    { word: 'Boomerang',         hint: 'Karma' },
    { word: 'Pavimento',         hint: 'Soffitto' },
    { word: 'Miraggio',          hint: 'Illusione' },
    { word: 'Oro',               hint: 'Ricco' },
    { word: 'Camaleonte',        hint: 'Mimetismo' },
    { word: 'Trump',             hint: 'Parrucca' },
    { word: 'Sesso',             hint: 'Attrito' },
    { word: 'Ex',                hint: 'Rimpianto' },
    { word: 'OnlyFans',          hint: 'Abbonamento' },
    { word: 'Tinder',            hint: 'Scorrere' },
  ],
};
